# x = int(input("enter first num: "))
# y = int(input("enter second num: "))
# print("sum is :",x+y)

x = int(input("enter empolyee num"))
y = input("enter employee name")
z = float(input("salary of employee"))
address = input("ente adress of employee")
married = bool(input("married"))
print("please confirm information")
print("enter empolyee name",x)
print("enter employe name",y)
print("employee salary",z)
print("employee address",address)
print("empolyee married",married)